@startuml
skinparam style strictuml
skinparam classAttributeIconSize 0
skinparam classFontStyle Bold

package model
{
    enum "<<enum>>\nGameColor" as GameColor
    {
        RED
        GREEN
        BLUE
        YELLOW
        ORANGE
        PINK
        GREY
        WHITE
        NONE
    }

    class MasterMindBoard
    {
        -lineCount : Integer
        -lineSize : Integer
        -currentLine : Integer
        +MasterMindBoard( lineSize:Integer, lineCount:Integer)
        +nextLine() : Boolean
        +verifyCurrentLine() : Boolean
        +getCellColor( line:Integer,  column:Integer)
        +setCellColor(line:Integer,  column:Integer)
        +generateSecretCombination()
    }


    MasterMindBoard o----> "-secretCombination\n\n* -board" MasterMindLine : very secret
    MasterMindBoard o----> "* -availableColors" GameColor : very secret

    class MasterMindGame
    {
         - nbRoud:Integer
         -  score:Integer
         -  nbPieceOfCombinaison:Integer
         -  nbTotalPiece:Integer
         -  nbTry:Integer
         -  playerName:String
         +<<create>>MasterMindBoard(playerName:String, nbRoud:Integer, nbPieceOfCombinaison:Integer, nbTotalPiece:Integer, nbTry:Integer)
         +getMasterMindBoard():MasterMindBoard
         +generateNewRound()
    }
    MasterMindGame o---> "-1\nmasterMindBoard"MasterMindBoard : play on

    class MasterMindLine
    {
        - size:Integer
        - wellPlaced = 0:Integer
        - wellChosen = 0:Integer
        +<<create>>MasterMindLine(size:Integer)

    + verifyCurrentLine(secretCombination:MasterMindLine):Boolean
    + getCellColor(index:Integer):GameColor
    + setCellColor(color:GameColor, index:Integer)

    }
    MasterMindLine o--> "*\n-cells"GameColor:contains
}

package view
{
    class StartWindow
    {
    }
    class GameWindow
    {
    }
    class EndWindow
    {
    }
}

package controller
{
    class GameMasterController
    {

    }

    GameMasterController --> "-1\nstartWindow" StartWindow : print
    GameMasterController --> "-1\ngameWindow" GameWindow : print
    GameMasterController --> "-1\nendWindow" EndWindow : print
}
@enduml