@startuml
skinparam style strictuml
skinparam classAttributeIconSize 0
skinparam classFontStyle Bold

package model
{
    class MasterMindBoard
    {
        lineCount : Integer
        lineSize : Integer
        currentLine : Integer
        NextLine()
        VerifyCurrentLine() : Boolean
        GetCellColor(int line, int column) : Color
        SetCellColor(Color color,int line, int column)
        GenerateSecretCombination()
    }
    enum "<<enum>>\nColor" as Color
    {
        RED
        GREEN
        BLUE
        YELLOW
        ORANGE
        PINK
        GREY
        WHITE
    }

    MasterMindBoard ----> "*\nsecretCombination\n\n**\nboard" Color
}

package view
{
}

package controller
{
}
@enduml